# documentation: https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  # disabled for now for testing...
  # # upgrade major and minor cargo dependencies soon
  # - package-ecosystem: "cargo"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   allow:
  #     - update-types:
  #       - "major"
  #       - "minor"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "12 4 * * MON,THU" # 4:12 in the morning twice per week
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all" # update both Cargo.toml and Cargo.lock
    cooldown:
      default-days: 3
    groups:
      # group patches for better visibility
      weekly-cargo-patches:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"

  # upgrade all GitHub Actions once per week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:23"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 3
