[workspace]
resolver = "2"

members = ["rosenpass", "to", "fuzz"]
default-members = ["rosenpass"]

[workspace.metadata.release]
# ensure that adding `--package` as argument to `cargo release` still creates version tags in the form of `vx.y.z`
tag-prefix = ""

[workspace.dependencies]
rosenpass = { path = "rosenpass" }
rosenpass-to = { path = "to" }
doc-comment = "0.3.3"
arbitrary = { version = "1.4.1", features = ["derive"] }
libfuzzer-sys = "0.4"
stacker = "0.1.21"
