// Additional rules for Marzipan extension

query_annotation: _QUERY ESCAPED_STRING
reachable_annotation: _REACHABLE ESCAPED_STRING

%extend query_decl: query_annotation "query" [ typedecl ";"] query "."     -> annotated_query_decl
                  | reachable_annotation "query" [ typedecl ";"] query "." -> reachable_query_decl

lemma_annotation: _LEMMA ESCAPED_STRING
%extend lemma_decl: lemma_annotation "lemma" [ typedecl ";"] lemma "." -> annotated_lemma_decl
