public_key = "/etc/rosenpass/connman/peer-b/rp-public-key"
secret_key = "/etc/rosenpass/connman/peer-b/rp-secret-key"
listen = ["[::]:9999"]
verbosity = "Quiet"

[[peers]]
public_key = "/etc/rosenpass/connman/peer-b/peer-a-rp-public-key"
endpoint = "198.51.100.10:9998"
device = "wg0"
peer = "zzqUfWGIil6QxrAGz77HE5BGUEdD2PgHYnCg3CDKagE="
extra_params = []
