public_key = "/etc/rosenpass/connman/peer-a/rp-public-key"
secret_key = "/etc/rosenpass/connman/peer-a/rp-secret-key"
listen = ["[::]:9998"]
verbosity = "Quiet"

[[peers]]
public_key = "/etc/rosenpass/connman/peer-a/peer-b-rp-public-key"
endpoint = "198.51.100.11:9999"
device = "wg0"
peer = "xTIB9kXjA/J6fQ6QtrQ5r4W4jV6L7B0W9Y5f2SOdT0k="
extra_params = []
