use serde::{Deserialize, Serialize};
use std::borrow::Borrow;
use std::path::PathBuf;

/// Example configuration generated by the command `rosenpass gen-config <TOML-FILE>`.
pub static EXAMPLE_CONFIG: &str = r###"public_key = "/path/to/rp-public-key"
secret_key = "/path/to/rp-secret-key"
listen = []
verbosity = "Verbose"

[[peers]]
# Commented out fields are optional
public_key = "/path/to/rp-peer-public-key"
endpoint = "127.0.0.1:9998"
# pre_shared_key = "/path/to/preshared-key"

# Choose to store the key in a file via `key_out` or pass it to WireGuard by
# defining `device` and `peer`. You may choose to do both.
key_out = "/path/to/rp-key-out.txt" # path to store the key
# device = "wg0" # WireGuard interface
#peer = "RULdRAtUw7SFfVfGD..." # WireGuard public key
# extra_params = [] # passed to WireGuard `wg set`
"###;

/// takes a path that can potentially start with a `~` and resolves that `~` to the user's home directory
///
/// ## Example
/// ```
/// use rosenpass::config::resolve_path_with_tilde;
/// std::env::set_var("HOME","/home/dummy");
/// let mut path = std::path::PathBuf::from("~/foo.toml");
/// resolve_path_with_tilde(&mut path);
/// assert!(path == std::path::PathBuf::from("/home/dummy/foo.toml"));
/// ```
pub fn resolve_path_with_tilde(path: &mut PathBuf) {
    if let Some(first_segment) = path.iter().next() {
        if !path.has_root() && first_segment == "~" {
            let home_dir = home::home_dir().unwrap_or_else(|| {
                log::error!("config file contains \"~\" but can not determine home diretory");
                std::process::exit(1);
            });
            let orig_path = path.clone();
            path.clear();
            path.push(home_dir);
            for segment in orig_path.iter().skip(1) {
                path.push(segment);
            }
        }
    }
}

fn toml_des<S: Borrow<str>>(s: S) -> Result<toml::Table, toml::de::Error> {
    toml::from_str(s.borrow())
}

fn toml_ser<S: Serialize>(s: S) -> Result<toml::Table, toml::ser::Error> {
    toml::Table::try_from(s)
}

fn assert_toml<L: Serialize, R: Borrow<str>>(l: L, r: R, info: &str) -> anyhow::Result<()> {
    fn lines_prepend(prefix: &str, s: &str) -> anyhow::Result<String> {
        use std::fmt::Write;

        let mut buf = String::new();
        for line in s.lines() {
            writeln!(&mut buf, "{prefix}{line}")?;
        }
        Ok(buf)
    }

    let l = toml_ser(l)?;
    let r = toml_des(r.borrow())?;
    anyhow::ensure!(
        l == r,
        "{}{}TOML value mismatch.\n  Have:\n{}\n  Expected:\n{}",
        info,
        if info.is_empty() { "" } else { ": " },
        lines_prepend("    ", &toml::to_string_pretty(&l)?)?,
        lines_prepend("    ", &toml::to_string_pretty(&r)?)?
    );
    Ok(())
}

pub fn assert_toml_round<'de, L: Serialize + Deserialize<'de>, R: Borrow<str>>(
    l: L,
    r: R,
) -> anyhow::Result<()> {
    let l = toml_ser(l)?;
    assert_toml(&l, r.borrow(), "Straight deserialization")?;

    let l: L = l.try_into().unwrap();
    let l = toml_ser(l).unwrap();
    assert_toml(l, r.borrow(), "Roundtrip deserialization")?;

    Ok(())
}

#[cfg(test)]
mod test {
    use super::*;
    #[test]
    fn test_resolve_path_with_tilde() {
        let test = |path_str: &str, resolved: &str| {
            let mut path = PathBuf::from(path_str);
            resolve_path_with_tilde(&mut path);
            assert!(
                path == PathBuf::from(resolved),
                "Path {:?} has been resolved to {:?} but should have been resolved to {:?}.",
                path_str,
                path,
                resolved
            );
        };
        // set environment because otherwise the test result would depend on the system running this
        std::env::set_var("USER", "dummy");
        std::env::set_var("HOME", "/home/dummy");

        // should resolve
        test("~/foo.toml", "/home/dummy/foo.toml");
        test("~//foo", "/home/dummy/foo");
        test("~/../other_user/foo", "/home/dummy/../other_user/foo");

        // should _not_ resolve
        test("~foo/bar", "~foo/bar");
        test(".~/foo", ".~/foo");
        test("/~/foo.toml", "/~/foo.toml");
        test(r"~\foo", r"~\foo");
        test(r"C:\~\foo.toml", r"C:\~\foo.toml");
    }
}
