# helper for the CLI and config-file backwards-compatibility checks.
#
# returns a shell snippet that rewrites a config file generated by
# `rosenpass gen-config` (of either the old or the new version) to reference
# the given key files, ports, etc.
#
# TODO: support more than one peer
# TODO: maybe also write test for this tool?
{
  # paths of the key files to reference
  ourPk,
  ourSk,
  peerPk,
  # value for the peer's endpoint; `null` removes the endpoint, making the
  # config responder-only
  peerEndpoint ? null,
  keyOut,
  # value for the listen list, e.g. `["127.0.0.1:51831"]`; `null` keeps the
  # generated value
  listen ? null,
  # output path to where the config file shall be written
  outputFilePath,
}:
let
  exprs = [
    "0,/^\\[\\[peers\\]\\]/ s|^public_key = .*|public_key = \"${ourPk}\"|"
    "0,/^\\[\\[peers\\]\\]/ s|^secret_key = .*|secret_key = \"${ourSk}\"|"
    "/^\\[\\[peers\\]\\]/,$ s|^public_key = .*|public_key = \"${peerPk}\"|"
    "/^\\[\\[peers\\]\\]/,$ s|^key_out = .*|key_out = \"${keyOut}\"|"
  ]
  ++ (
    if peerEndpoint == null then
      [ "/^endpoint = /d" ]
    else
      [ "/^\\[\\[peers\\]\\]/,$ s|^endpoint = .*|endpoint = \"${peerEndpoint}\"|" ]
  )
  ++ (if listen == null then [ ] else [ "s|^listen = .*|listen = ${listen}|" ])
  ++ [
    # remove exchange_command – this is currently a known incompatibility
    # see https://github.com/rosenpass/rosenpass/issues/1134

    # single-line form: `exchange_command = [ ... ]`
    "/^exchange_command = .*\\]/d"
    # multi-line form: `exchange_command = [` followed by one item per line
    "/^exchange_command = /,/\\]/d"
  ];
in
"sed -i "
+ builtins.concatStringsSep " \\\n  " (builtins.map (e: "-e '${e}'") exprs)
+ " ${outputFilePath}"
