# Backwards-compatibility integration checks of CLI and config file
#
# 1. test key exchange between old and new rosenpass binary with CLI
#    (`rosenpass exchange` grammar)
# 2. test validation (`rosenpass validate` with new binary) of configuration
#    files generated by the old rosenpass version
{
  pkgs,
  lib,
  rosenpassOld,
  rosenpassNew,
  ...
}:
let
  rosenpassKeyFolder = "/var/secrets"; # directory to store keys during tests

  toolOld = "${rosenpassOld}/bin/rosenpass";
  toolNew = "${rosenpassNew}/bin/rosenpass";

  # default timeout for every single command in the `testScript` – the entire `testScript` may take much longer
  defaultTimeout = toString 60;

  # tool to insert paths to key files into TOML config file
  adaptGenConfig = import ./adapt-gen-config.nix;

  # Shell scripts adapting the config files generated by the old rosenpass
  # version; wrapped as store paths so that the test script only references
  # quote-free paths.
  #
  # - server config has `listen` but no peer `endpoint` (responder-only)
  # - client config keeps its empty `listen` list (binds to default ports)
  adaptServerConfig = pkgs.writeShellScript "adapt-server-config" (adaptGenConfig {
    ourPk = "${rosenpassKeyFolder}/server.pk";
    ourSk = "${rosenpassKeyFolder}/server.sk";
    peerPk = "${rosenpassKeyFolder}/client.pk";
    listen = ''["127.0.0.1:51831"]'';
    peerEndpoint = null;
    keyOut = "/root/configfile-server.osk";
    outputFilePath = "/root/server.toml";
  });
  adaptClientConfig = pkgs.writeShellScript "adapt-client-config" (adaptGenConfig {
    ourPk = "${rosenpassKeyFolder}/client.pk";
    ourSk = "${rosenpassKeyFolder}/client.sk";
    peerPk = "${rosenpassKeyFolder}/server.pk";
    peerEndpoint = "127.0.0.1:51831";
    keyOut = "/root/configfile-client.osk";
    outputFilePath = "/root/client.toml";
  });
in
{
  name = "rosenpass CLI and config file backwards compatibility";

  nodes.machine = {
    systemd.services = {
      # test CLI compatibility with `rosenpass exchange` grammar
      # - `rosenpass-cli-server` uses old rosenpass version and the deprecated `private-key` spelling
      # - `rosenpass-cli-client` uses new rosenpass version and the current `secret-key` spelling
      rosenpass-cli-server = {
        description = "Rosenpass (old version) called via CLI";
        wantedBy = [ ];
        serviceConfig = {
          Restart = "on-failure";
          RestartSec = 2;
        };
        script = ''
          ${toolOld} exchange \
            public-key ${rosenpassKeyFolder}/server.pk \
            private-key ${rosenpassKeyFolder}/server.sk \
            listen 127.0.0.1:51821 \
            verbose \
            peer \
            public-key ${rosenpassKeyFolder}/client.pk \
            outfile /root/cli-server.osk
        '';
      };
      rosenpass-cli-client = {
        description = "Rosenpass (new version) called via CLI";
        wantedBy = [ ];
        serviceConfig = {
          Restart = "on-failure";
          RestartSec = 2;
        };
        script = ''
          ${toolNew} exchange \
            public-key ${rosenpassKeyFolder}/client.pk \
            secret-key ${rosenpassKeyFolder}/client.sk \
            listen 127.0.0.1:51822 \
            verbose \
            peer \
            public-key ${rosenpassKeyFolder}/server.pk \
            endpoint 127.0.0.1:51821 \
            outfile /root/cli-client.osk
        '';
      };

      # test config file compatibility with `rosenpass exchange-config`
      # - config files generated by the old rosenpass version
      # - config files will be adapted (fill in key paths, port, etc.) by `testScript`
      # - `testScript` will run two instances of the new version binary
      rosenpass-configfile-server = {
        description = "Rosenpass (new version) running a config file generated by the old version";
        wantedBy = [ ];
        serviceConfig = {
          Restart = "on-failure";
          RestartSec = 2;
        };
        script = ''
          ${toolNew} exchange-config /root/server.toml
        '';
      };
      rosenpass-configfile-client = {
        description = "Rosenpass (new version) running a config file generated by the old version";
        wantedBy = [ ];
        serviceConfig = {
          Restart = "on-failure";
          RestartSec = 2;
        };
        script = ''
          ${toolNew} exchange-config /root/client.toml
        '';
      };
    };
  };

  testScript = ''
    machine.wait_for_unit("multi-user.target")

    # generate keys with old rosenpass binary
    machine.succeed("mkdir -p ${rosenpassKeyFolder}")
    machine.execute("${toolOld} gen-keys -p ${rosenpassKeyFolder}/server.pk -s ${rosenpassKeyFolder}/server.sk", check_return=True, timeout=${defaultTimeout})
    machine.execute("${toolOld} gen-keys -p ${rosenpassKeyFolder}/client.pk -s ${rosenpassKeyFolder}/client.sk", check_return=True, timeout=${defaultTimeout})

    # Test 1: key exchange between the old and the new binary, both started via CLI (`rosenpass exchange` grammar)
    machine.execute("systemctl start rosenpass-cli-server.service", check_return=True, timeout=${defaultTimeout})
    machine.execute("systemctl start rosenpass-cli-client.service", check_return=True, timeout=${defaultTimeout})
    machine.wait_until_succeeds("test -s /root/cli-server.osk", timeout=${defaultTimeout})
    machine.wait_until_succeeds("test -s /root/cli-client.osk")
    machine.wait_until_succeeds("cmp /root/cli-server.osk /root/cli-client.osk")

    # generate configuration files with old rosenpass binary
    #
    # This is only a backwards-compatibility test (not forward-compatibility) because
    # the config files are never generated with new rosenpass binary.
    machine.execute("${toolOld} gen-config /root/server.toml", check_return=True, timeout=${defaultTimeout})
    machine.execute("${toolOld} gen-config /root/client.toml", check_return=True, timeout=${defaultTimeout})
    # put config keys into the config files (key paths, ports, etc.)
    machine.succeed("${adaptServerConfig}")
    machine.succeed("${adaptClientConfig}")
    # pin the legacy protocol version explicitly in both configs.
    machine.succeed("sed -i '/^key_out = /a protocol_version = \"V02\"' /root/server.toml")
    machine.succeed("sed -i '/^key_out = /a protocol_version = \"V02\"' /root/client.toml")
    # print final config files
    machine.succeed("echo server config:")
    machine.succeed("cat /root/server.toml")
    machine.succeed("echo client config:")
    machine.succeed("cat /root/client.toml")

    # Test 2: new rosenpass version must accept the config files generated by old version
    machine.execute("${toolNew} validate /root/server.toml 2>/root/server-validate.log", check_return=True, timeout=${defaultTimeout})
    machine.execute("${toolNew} validate /root/client.toml 2>/root/client-validate.log", check_return=True, timeout=${defaultTimeout})
    # TODO: maybe check the tool's output? I think this is too unstable and also, the tools exit code pretty much says it all...
    # print validation result for easier debugging
    machine.succeed("echo server config validation result:")
    machine.succeed("cat /root/server-validate.log")
    machine.succeed("echo client config validation result:")
    machine.succeed("cat /root/client-validate.log")

    # Test 3: key exchange between two new-version instances configured with the old-version config files
    machine.execute("systemctl start rosenpass-configfile-server.service", check_return=True, timeout=${defaultTimeout})
    machine.execute("systemctl start rosenpass-configfile-client.service", check_return=True, timeout=${defaultTimeout})
    machine.wait_until_succeeds("test -s /root/configfile-server.osk", timeout=${defaultTimeout})
    machine.wait_until_succeeds("test -s /root/configfile-client.osk", timeout=${defaultTimeout})
    machine.wait_until_succeeds("cmp /root/configfile-server.osk /root/configfile-client.osk", timeout=${defaultTimeout})
  '';
}
