Protocol: {
  shape: sequence_diagram
  ini: "Initiator"
  res: "Responder"
  ini -> res: "InitHello"
  res -> ini: "RespHello"
  ini -> res: "InitConf"
  res -> ini: "EmptyData"
}

Envelope: "Envelope" {
  shape: class
  type: "1"
  '': 3
  payload: variable
  mac: 16
  cookie: 16
}

Envelope.payload -> InitHello
InitHello: "InitHello (type=0x81)" {
  shape: class
  sidi: 4
  epki: 800
  sctr: 188
  peerid: 32 + 16 = 48
  auth: 16
}

Envelope.payload -> RespHello
RespHello: "RespHello (type=0x82)" {
  shape: class
  sidr: 4
  sidi: 4
  ecti: 768
  scti: 188
  biscuit: 76 + 24 + 16 = 116
  auth: 16
}

Envelope.payload -> InitConf
InitConf: "InitConf (type=0x83)" {
  shape: class
  sidi: 4
  sidr: 4
  biscuit: 76 + 24 +16 = 116
  auth: 16
}

Envelope.payload -> EmptyData
EmptyData: "EmptyData (type=0x84)" {
  shape: class
  sidx: 4
  ctr: 8
  auth: 16
}

Envelope.payload -> Data
Data: "Data (type=0x85)" {
  shape: class
  sidx: 4
  ctr: 8
  data: variable + 16
}

Envelope.payload -> CookieReply
CookieReply: "CookieReply (type=0x86)" {
  shape: class
  sidx: 4
  nonce: 24
  cookie: 16 + 16 = 32
}

RespHello.biscuit -> Biscuit
InitConf.biscuit -> Biscuit
Biscuit: "Biscuit" {
  shape: class
  peerid: 32
  no: 12
  ck: 32
}
