[[entries]]
entry_type = "Const"
description = "test setup: peer a secret key"
name = "peer_a_sk"
code_location = "tests/test_vector_crypto_server.rs:96"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Const"
description = "test setup: peer a public key"
name = "peer_a_pk"
code_location = "tests/test_vector_crypto_server.rs:97"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Const"
description = "test setup: peer b secret key"
name = "peer_b_sk"
code_location = "tests/test_vector_crypto_server.rs:102"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Const"
description = "test setup: peer b public key"
name = "peer_b_pk"
code_location = "tests/test_vector_crypto_server.rs:103"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Const"
description = "pre-shared key"
name = "psk"
value = "HpzKswK7GXMRFNVx0mkbVOTBApFjL+lzpjfQlsHWAHA="
code_location = "tests/test_vector_crypto_server.rs:106"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[0]"
value = "3hAsF7VJfzbcFNNynG6xiQ=="
code_location = "tests/test_vector_crypto_server.rs:168"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[1]"
value = "Kw9H7AaYd/0MpJEL5A4k6A=="
code_location = "tests/test_vector_crypto_server.rs:173"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[0]"
value = "03icmzlBBeUeB/DGwjo6Tcu+hlwf6zn07JG91fWbZEQ="
code_location = "tests/test_vector_crypto_server.rs:178"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[1]"
value = "EsB+Q4yv4xS6ZU/O3f+d+OYkJEow7cm5MXHiKYdIlRw="
code_location = "tests/test_vector_crypto_server.rs:180"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[0]"
value = "pdB0oGCDoJGQDO/fSeQHRw=="
code_location = "tests/test_vector_crypto_server.rs:168"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::cookie_secrets[1]"
value = "g15TxPcof7F1WNXFbRVW1w=="
code_location = "tests/test_vector_crypto_server.rs:173"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[0]"
value = "Mn5ymqEmZCM/aqbb3KbWllEp6xK6D48mgawYvNWcpTo="
code_location = "tests/test_vector_crypto_server.rs:178"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "CryptoServer::biscuit_keys[1]"
value = "9Ds8hJpuiRutPH1jeiMsheqgTdG/DkLeHjPGHVGd/t4="
code_location = "tests/test_vector_crypto_server.rs:180"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:69"

[[entries]]
entry_type = "Const"
name = "hs.cookie_value.value"
value = "l+aBifkwvKFx3hhwhtYuhQ=="
code_location = "rosenpass/src/protocol/protocol.rs:3569"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Const"
name = "hs.core.sidi"
value = "QXKCmg=="
code_location = "rosenpass/src/protocol/protocol.rs:3582"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Const"
name = "hs.eski"
value = "Daet8SGz3gdsCHoyZ9N+4stAays3FVIIj1C0EpYVIeQ7T9aaQzkiZEW2XrhAxed1JIRDtZzM+GGb8rl+9YaHtfZG4BpuMaIEUlZrd/oCcMxwitByg9MKLwOysqlHMVtsqlEBeWzAWPkmu1g1snqDcprFq7nMU9G8AcOAbEfO4BCB5pbN1uqXFEZkV/cB6Blj8GAH0Zdi5sDPGigc45SikRgP9bxdVcqGWLVvkOyeNCuafzszZURMUVm9juwDUDqE69iz5IlDK2SzxMKW6wu/WgmhDthJ54hTAFiV4ubPaEBXEUdVYPMCU0Aa49i/MMw2uPSd9gTE/QI59Qgju3taCjGWpPJ2UygDVOJ2ZJifZqEgPCtK29AntnaE4JbF86cqy3YnPQe+3Wt4gMRjq8hMJNhHPYCuElcj2Iq7hqSyjezHlEwYXUvHNYSSONwtjDMSKMpWMxsj6WbHUjBNleCcnwCUxzpoEHl3wWBViDq+EiQyPdBSZLh/EUm1csuAWqowSJFhO2p4IDsYiuYlEGoER1afBIRXTNlQb1uhkmq5XtsunEgPQsGearpVbaS5BJhKNyKdCOxJGZcygutu1AvPTtssjRJp7Nu/hFWLRWR3m0dX+cxHG+MWEVpdDHGcTCcLCfhTOik4ZFCueOIZKtbNJ+N2O0S4oLA4ysLEWtZ3r8u11uAwWRMKSfyfjcIxNsCpNNuX8qY5RsqYIwDNXwaCBXM9B0aqcIxbtfKdCmJjygcP4XdlK0MSNXspbwFPQaWgvDnNCCkfNJpU48MXTvd1KTsHdWmAXkWMvGhp7gwmOedYUetnR+uTbbwCZ5gazydU5AOPfKU0EcMGthGu+ugfKGsg/tTJrnNW8KRe96d3DCosJ+AEqWiTbAU7AQO0VAwamDV5iuiUdRe3U9FDNMkeqeLE/stE6ewdZ4N2gxmmyyq6dVqjEOvCJsEr8kCOMuZ8DpOIzdKn7pzFR0hf//kPgIlNCFp8odWYcqqNZ/YUJ9g/xFKu1JmbrXaRFHt0x/Vajkxc56sL0/msinfPz8M7TTY01gmgf/kcOLFXfiZfqKQyUXJOVAREoDVvjaSuEYcX7Xw7M4iG5nwdVpJN0exhPkdR/iB0CgysmsnAjQwC18Q/PTLFQJM/FRiu6booLUhQKFVtpdFZj1Mi5GDAaXd23CIFMMoFjpcHmoYM8vhDaFG+TnOeWUIFZ/EnwHLGvfw74Dk8kieeK1wrkeqUIrSNbIVA0zTINliFfAsed2iEzZFtFQpaPxWcDqNFOnIndvolN/wWnACrKYI4mwim3ruDDyCFuNC3+Soe9UvELnMJF/d6QbiHziWu6TtPHuAi0YUUTNoslZsr56W7Aec7FZQjmNmy5ZVNBjNtxbIQ+kq1C4G+qSQm0JyZSwCxJlQf2EwZAgwr+cNF+assJNUsaFapEyxOInl7R3ADaKNzmadsRxzE/PTNwFyZJ1U98mu2GpyLhGCJRoNWsppalgEwSHwuskB0X1xEHTN7yCQQa4A9Hyqy8wBQ/uxhcByazMR1HyGalHCIxNevIxB0ArI+eKuVcZQSoEJ39qcPyjlrEmWFG1sFYfQpzzhts5HFuyWYvFM8wGXJ2fTATpyzrgSPE/MfSUgslxcRHJIJrMoJ+zoeQHCzuufECXOanTPAX9uOoHrIm6DPRKHPjIdaRWws/Zmp/Qk5VxV7ixB/28V3vkdUmFRS8FwPn4pfRRJNfaQn9CElsiZm+tMpEkx+KmAeA8hiOkYUj5GdzVsDEiU/6ztZc4cX+jC3Imk+2syjeaFQ6wGMkSqN2KdKKSOMe7Z9QSmrLFUhkNlIoaIdCykSXMlAMlpnJAB40OLPxxm+/XLNSuFllQcfAZNZU5tWIlg4IbFOewyVGwqGGSTJQvY6ccktu2BH/QK3oJYb5OcitYWtVwZTnUe1jFuTLTNln+QnSstc40MgU9yAXFpiklh75IZzrRkrEQtI7pQtu1kpxiZLmxcB8IiUs5kq9wi2MYoP4UmB1XCiyyw96ROoVeQmfQJU2nNaMhKe14kTbeZyJ1Srx6glaPfoDoN1VeUSGEkhrOzTHbxOc9HhcgyNwMT4yflDRoKLzvekcNX+kzsDgRu9EinCdrEg8Ga5sm2GArc0U8AweIPBvXmEwJ/++ctCMfUaQY/yw84HUoY1z3rxN/OxrK2G"
code_location = "rosenpass/src/protocol/protocol.rs:3589"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Const"
name = "hs.core.ck"
value = "jkxc56sL0/msinfPz8M7TTY01gmgf/kcOLFXfiZfqKQyUXJOVAREoDVvjaSuEYcX7Xw7M4iG5nwdVpJN0exhPkdR/iB0CgysmsnAjQwC18Q/PTLFQJM/FRiu6booLUhQKFVtpdFZj1Mi5GDAaXd23CIFMMoFjpcHmoYM8vhDaFG+TnOeWUIFZ/EnwHLGvfw74Dk8kieeK1wrkeqUIrSNbIVA0zTINliFfAsed2iEzZFtFQpaPxWcDqNFOnIndvolN/wWnACrKYI4mwim3ruDDyCFuNC3+Soe9UvELnMJF/d6QbiHziWu6TtPHuAi0YUUTNoslZsr56W7Aec7FZQjmNmy5ZVNBjNtxbIQ+kq1C4G+qSQm0JyZSwCxJlQf2EwZAgwr+cNF+assJNUsaFapEyxOInl7R3ADaKNzmadsRxzE/PTNwFyZJ1U98mu2GpyLhGCJRoNWsppalgEwSHwuskB0X1xEHTN7yCQQa4A9Hyqy8wBQ/uxhcByazMR1HyGalHCIxNevIxB0ArI+eKuVcZQSoEJ39qcPyjlrEmWFG1sFYfQpzzhts5HFuyWYvFM8wGXJ2fTATpyzrgSPE/MfSUgslxcRHJIJrMoJ+zoeQHCzuufECXOanTPAX9uOoHrIm6DPRKHPjIdaRWws/Zmp/Qk5VxV7ixB/28V3vkdUmFRS8FwPn4pfRRJNfaQn9CElsiZm+tMpEkx+KmAeA8hiOkYUj5GdzVsDEiU/6ztZc4cX+jC3Imk+2syjeaFQ6wGMkSqN2KdKKSOMe7Z9QSmrLFUhkNlIoaIdCykSXMlAMlpnJAB40OLPxxm+/XLNSuFllQcfAZNZU5tWIlg4IbFOewyVGwqGGSTJQvY6ccktu2BH/QK3oJYb5OcitYWtVwZTnUe1jFuTLTNln+QnSstc40MgU9yAXFpiklh75IZzrRkrEQtI7pQtu1kpxiZLmxcB8IiUs5kq9wi2MYoP4UmB1XCiyyw96ROoVeQmfQJU2nNaMhKe14kTbeZyJ1Srx6glaPfoDoN1VeUSGEkhrOzTHbxOc9HhcgyNwMT4yflDRoI="
code_location = "rosenpass/src/protocol/protocol.rs:3590"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 1"
value = "ANyglK92Pnah2o8s17KVv6jHYiM8XENdWUte4eTcphc="
code_location = "rosenpass/src/protocol/protocol.rs:3597"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Const"
value = "vsajMkGfwRqoqTKqFLFoDNwohNrLXFoLz5WueWR3kEE="
code_location = "rosenpass/src/protocol/protocol.rs:3272"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:23"

[[entries]]
entry_type = "Const"
value = "LSDvlDCT8Cd/YoX2YZCQh8drl8l85thyfHhz/fQUybftn25Yn4DxuvlD95EN0QXONeusNr2GuSeEFmt/v2iOWo7RFlcjMilLB4tjxuY6OWFvWYzmVsb+9WEVXwyWXiVq2H2mMOsZN+0p9at3An1wQ00iimTOSXis6f3CzKYv4WkxM2YEkmyKNMwPB7p5DeejaQCSdH5NkTxA0vJtbix5wAHb+e9KVvAZ6XFSmYg5hOOWvv7w/x7Xe2Tf3H8="
code_location = "rosenpass/src/protocol/protocol.rs:3273"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:23"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 2"
value = "n35rCDSBUCgzbe+UrBtsew/uIes+9e9xbeBBkuza8/Q="
code_location = "rosenpass/src/protocol/protocol.rs:3612"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
name = "ih.pidi_ct"
value = "JMVHLTupGo6CHYNrAZADzqPE2vcvvGWOZ8kmsiejnR+QMGaCjmsP1OEKy/j0Benm"
code_location = "rosenpass/src/protocol/protocol.rs:3625"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 3"
value = "Qhky2gp3xzizdAjOhXCVBTQ0udqGnEQueYEHEHLOeNY="
code_location = "rosenpass/src/protocol/protocol.rs:3626"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 4"
value = "qq7vQGveZNY8NvSir1Cig0ZpErAkwEGD9jq5XhCDHWQ="
code_location = "rosenpass/src/protocol/protocol.rs:3637"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
name = "ih.auth"
value = "gCH9ZrD16I7E9KLUlYHlWg=="
code_location = "rosenpass/src/protocol/protocol.rs:3646"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
name = "hs.core.ck 5"
value = "wqLXpfoT4wE2Zmitl8xR8nSGob0PEbeBQ/RwkKbHeiI="
code_location = "rosenpass/src/protocol/protocol.rs:3647"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:44"

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "tests/test_vector_crypto_server.rs:137"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 4"
value = "ANyglK92Pnah2o8s17KVv6jHYiM8XENdWUte4eTcphc="
code_location = "rosenpass/src/protocol/protocol.rs:3704"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 5"
value = "n35rCDSBUCgzbe+UrBtsew/uIes+9e9xbeBBkuza8/Q="
code_location = "rosenpass/src/protocol/protocol.rs:3713"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 6"
value = "Qhky2gp3xzizdAjOhXCVBTQ0udqGnEQueYEHEHLOeNY="
code_location = "rosenpass/src/protocol/protocol.rs:3725"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 7"
value = "qq7vQGveZNY8NvSir1Cig0ZpErAkwEGD9jq5XhCDHWQ="
code_location = "rosenpass/src/protocol/protocol.rs:3735"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr IHR 8"
value = "wqLXpfoT4wE2Zmitl8xR8nSGob0PEbeBQ/RwkKbHeiI="
code_location = "rosenpass/src/protocol/protocol.rs:3744"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Const"
name = "session_id"
value = "Mcs4cg=="
code_location = "rosenpass/src/protocol/protocol.rs:3752"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 3"
value = "7yMWbSXZIe5fE2ZTed+mdZ2ohrrjXeZomUG5cFM1bAY="
code_location = "rosenpass/src/protocol/protocol.rs:3760"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Const"
value = "oWCX4+9OFw0HfJvirAAtqyXmsZAh84QCdKO99MNxn3I="
code_location = "rosenpass/src/protocol/protocol.rs:3272"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:23"

[[entries]]
entry_type = "Const"
value = "2Lax1SI57cWfVUhDqHen5Gd9duJ1unvishxQ2m1ESFQ6t2efaqjPj2IUDZqtzDL4TjHOwcfwBeWH7rSwlRjztojJZWJ/MKkdJxo4zfImNVTKb5LqoP7GqEWhCtCuL/vakO9y3IWLX3jicp5V7/Riu4GZRkPlta35pXhCXmPKgMKOlAbq1meCGWo3lI9ou2jTkNOSxOgUIFxv0puQtii91Wlxc+jSQg5MMVTdmF/nlzpSK+FEefNWSfiOh2Xxtiz7wNbz3S3jA8ysdXumkPJbOpRJseovyTHDeWUeymDolv7+BFa9iaRWwJGz1TuydZTvtyuM4NTnABu74pH9iQjsj63ie1ju8MwqksCC/JNL+QMnqQamXFvzKZ0vBgdadgBaeF/CMm1Dbm9p26Sw/n7eFXrlnmHbqM6nwT0OtIZzhLFO84Sw0I3WOimVeNZ9D0zbb5n6t6Mb42dQLkr0GnK4UwcugHtsqmnrsB4UWUn/HL9hsYqtC0zyWg4nDdnPQYeKpobrESS1eGe0i/jceyzao48I9w3SJMyEe7vALbqtGjxo3nuhBeU0hJsi7ENFvhNT76LF/lehgBrFy81XK1O7Xg/vND2lEZJTFRAlZ68WNXr0F+ETGT4H+seTFyHujXtOPOQLAG6euWPZqEowbwB/gGV/iG5NkJrMUTC4Rx9mePEkjgTnCnv0ZuzvGYlgIueOn31gJYDrUk/nSEAo24IGqGsqwsLSf2VYv8wmY7Thm7n1MKYJS0HBSQb8F/b+7KOkaxrpLIO61mWlpC1uVGoD/qjpIw4pMLr1XFHgyEvkaZPUzFTFjWsvc/yp8jJAmSNn93i3PZ1SyRM1VCF+FCbDuIIOk6uU+ufpNABwsa584SKIrSlJgk1+NY3yzYYtZO9Aa5FUcihGpIjvwoeQq+eF8VttVvaztwgvpGCjoWiiOQtB5mKpuU5q9uDKsHq9EhLJa1/siwIcQXKwO1XGcmdKVG1WjLTXJHj5FbmeX9AcpRza0xW5D5ySf5yYiFiLzR+h"
code_location = "rosenpass/src/protocol/protocol.rs:3273"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:23"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 4"
value = "9Abzi5fhH8oPjxMIC4e9vWRiKpjMqKWw0CXRv6UDGqI="
code_location = "rosenpass/src/protocol/protocol.rs:3775"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Const"
value = "LvQgDUBiEIM2fNguegD58HaZHSr7AIZylcjRz+c01XA="
code_location = "rosenpass/src/protocol/protocol.rs:3272"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:23"

[[entries]]
entry_type = "Const"
value = "SbOKCKcoMulqTmiB5EPzx5mtnOXvbzJ46KmcVYb2bgII4gwCOw9beDARBfe1RKloc2xHA310ne8jlTWa27UM12828xMciKL0nt+SCy8hoX92mGTp+cdA0BUEBLSmB9Kn5nms6/PUUv7bdxBxdjoulBZfRXwbGMgaCLWljO3q9itqjvMcTL5iaN6CRJV4M6JoprEAdzbIXDfTLD8ZDxXpZvXXgCcopk4HQi5o15DL6iN84pPAmFt+Kqpwwnc="
code_location = "rosenpass/src/protocol/protocol.rs:3273"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:23"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 5"
value = "2KXVrZ6Kk2+wi0iJ20I1UKNJ+cKPFRpuGOPzEc0OMBY="
code_location = "rosenpass/src/protocol/protocol.rs:3790"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
value = "EFsT4OojPVLdqd9Mt5orDqYoH0uqWZGRe1duRmPfLiABAAAAAAAAAAAAAADYpdWtnoqTb7CLSInbQjVQo0n5wo8VGm4Y4/MRzQ4wFg=="
code_location = "rosenpass/src/protocol/protocol.rs:3345"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:31"

[[entries]]
entry_type = "Const"
description = "Biscuit key after being cycled"
name = "CryptoServer::biscuit_key[r]"
value = "aYVS6QnJi45X1XuVLCODmGorUEG0paHA8se79EQbGvU="
code_location = "rosenpass/src/protocol/protocol.rs:1442"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:127"

[[entries]]
entry_type = "Const"
value = "WsuMSv2Xb6ylG+4XaffpN5VgpkJsRfjI"
code_location = "rosenpass/src/protocol/protocol.rs:3362"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:31"

[[entries]]
entry_type = "Output"
value = "2suMSv2Xb6ylG+4XaffpN5VgpkJsRfjIr0m4q6cN1dZFb16n8TBpYzD0JJmqwVOYry9RH4B+OToN2u5uAe88EMKzH2u/Tkxo4IhZ24MVb9EfH1yssazL8KOqF4SS0x9kGW7HH1D2EusDohJ4DE9crHFsK8E="
code_location = "rosenpass/src/protocol/protocol.rs:3370"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:31"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 6"
value = "K5lI4BZkuDYuloZODl4AknKct0U8BJVNIDvLibskADk="
code_location = "rosenpass/src/protocol/protocol.rs:3799"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
name = "chaining_key_ihr RHR 7"
value = "a52k/hon+HVXlAt08cL9J82B63RLkWxd+0PvF4g5bfM="
code_location = "rosenpass/src/protocol/protocol.rs:3808"
test_vec_set_code_location = "rosenpass/src/protocol/test_vector_sets.rs:84"

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "tests/test_vector_crypto_server.rs:137"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "tests/test_vector_crypto_server.rs:137"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Output"
description = "message exchanged by the protocol parties"
name = "message"
code_location = "tests/test_vector_crypto_server.rs:137"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
offload = true

[[entries]]
entry_type = "Output"
description = "final exchanged key"
name = "exchanged_key"
value = "TPBC02VC6Lxl+k2yr33S9TuWV9kzlr8aKq9Fy9UGbAU="
code_location = "tests/test_vector_crypto_server.rs:154"
test_vec_set_code_location = "rosenpass/tests/test_vector_crypto_server.rs:33"
