name: rosenpass - protocol - benchmark

on:
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:
  push:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  proto-benchmark:
    strategy:
      fail-fast: true
      matrix:
        bits: [32, 64]
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - run: echo "RUST_TARGET_FLAG=" > $GITHUB_ENV
        if: ${{ matrix.bits == 64 }}

      - name: 🛠️ Setup Ubuntu x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add i686-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: 🛠️ Setup Ubuntu x64
        if: ${{ matrix.bits == 64 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add aarch64-unknown-linux-gnu


      # Set up 32 bit systems

      - name: 🛠️ Config Linux x86
        run: |
          echo "RUST_TARGET_FLAG=--target=i686-unknown-linux-gnu" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'ubuntu-latest' }}

      # Benchmarks ...

      - name: 🏃🏻‍♀️ Benchmarks
        run: cargo bench -p rosenpass --bench trace_handshake -F trace_bench --verbose $RUST_TARGET_FLAG >bench.json

      - name: Upload benchmarks
        uses: cryspen/benchmark-upload-and-plot-action@v2
        with:
          name: rosenpass protocol benchmarks
          group-by: 'os,arch,category,group'
          schema: 'os,arch,category,group,name'
          input-data-path: bench.json
          benchmark-data-dir-path: dev/bench/protocol
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # NOTE: pushes to current repository
          gh-repository: github.com/${{ github.repository }}
          auto-push: true

  ciphers-protocol-bench-status:
    if: ${{ always() }}
    needs: [proto-benchmark]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }}
        run: exit 1
