name: PR Validation on Mac
on:
  workflow_dispatch:
permissions:
  checks: write
  contents: write
concurrency:
  group: manual-mac-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  qc:
    uses: ./.github/workflows/qc-mac.yaml
    permissions:
      checks: write
      contents: read
  nix:
    uses: ./.github/workflows/nix-mac.yaml
    permissions:
      contents: write
