    # TODO: finish defining these (comes from Cryptoverif)
    #param_decl: "param" _non_empty_seq{IDENT} options "."
    #proba_decl: "proba" IDENT ["(...)"] options "."
    #letproba_decl: "letproba" IDENT ["(...)"] "= ..." "."
    #proof_decl: "proof" "{" proof "}"
    #def_decl: "def" IDENT "(" _maybe_empty_seq{typeid} ")" "{" decl* "}"
    #expand_decl: "expand" IDENT "(" _maybe_empty_seq{typeid} ")" "."
